// <auto-generated />
namespace ViewModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AmendedExercisetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AmendedExercisetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201302200756270_Amended Exercise table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
